# Generated by Django 4.2.4 on 2023-09-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IAP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchace',
            name='product_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchace',
            name='purchase_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchace',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
